### ISSUE TITLE
Github Actions Lint

### ISSUE THREAD

**Issue by cdnninja** [fuatakgun/kia_uvo#143]
To continue discussions around future github actions.  

I wanted to get your thoughts @dahlb  on this demo: https://github.com/peter-evans/slash-command-dispatch/pull/28

It looks like it can get around the github limitation arounds pushing commits.  So if implemented I would think we do the following:

1. Keep the existing checks, they wouldn't "fix" anything just tell you if issues exist.
2. Comment in the PR someone created to let them know /black or others are available to them. 
3. If the run /black it resolves the issue in the commit and checks restart. 

I haven't got this working yet in my repo but it seems to work in the demo.

**Comment by dahlb** [comment]
if I understand this new approach sounds much better but it still feels very manual.  I'd rather it be something that just happened without having to think about it every time.  

The post commit hook would've worked better than the last PR done fixes which caused a merge conflict and lost a bug fix.  

I somewhat understand the hesitancy to fully automated solutions but given how widely it sounds like black is used I would think it is large enough to trust as a post commit solution, it is git even if it was force pushed a bad master commit it should be fixed by either a simple revert or worst case looking through the git logs for the lost old master.

I haven't used actual pre-commit git (not github) hooks but could we put it there so it would be seen in the PR but wouldn't require anybody to think about it after they initially installed black locally?

**Comment by cdnninja** [comment]
If they have black locally the actions will pass when code is checked in.   This is more for people who aren't using black locally.   Two things I will look for:

1. An example of doing that full automated commits to master.  I haven't seen anyone do that yet.  
2. I will see if this /command method works for remote forks.  It claims it will.  If so I can use the same token method to make it fully automated.  This is an access issue currently.

**Comment by dahlb** [comment]
@cdnninja they might have black locally like I do, but for the current actions to pass they have to be manually running black constantly before every commit.  That is what I am finding far from seamless and why I've been suggesting either a git pre-hook or a github post hook.

Even with the black run on a PR of the PR that involves them manually merging that PR and waiting for the tests to rerun and pass, again not feeling very seamless. 

Does black expect exceptions to be used like a tool I once used call code climate? Otherwise the manual adjusts are making little sense to me because if black was ignored and merged it would just come up to be fixed during all subsequent PR.  I'm not sure I fully understand the command method but I think its flow would involve a maintainer thinking to manually add a comment of /command to a PR they think doesn't look right or is already failed a CI test which would then create a second PR to be manually merged into the initial PR.  

I think the pre-commit hook would get you the flow you're expecting where all the black changes show up for review in the PR, the only down side I've heard about pre-commit hooks in git is they can be complicated if somebody is developing on windows; but I haven't used them myself and black (python) seems pretty good at being platform safe.

**Comment by cdnninja** [comment]
Right now it is a pre-commit hook.  However the commit isn't occurring in a fork the token has access to commit to.  I think I have an idea on how to fix this.  It will take time though.  I will keep you posted.

**Comment by cdnninja** [comment]
@dahlb  Could you try create a PR with a black formatting issue against the master branch here? https://github.com/cdnninja/kia_uvo  Please ensure the default checkbox of allowing contributors access is still checked - this is checked by default. 

Here is an example how it works within the branch: https://github.com/cdnninja/kia_uvo/pull/9  ignore the second merge - that was a spelling mistake in the master that was caught by codespell check - it can't auto fix that.

**Comment by dahlb** [comment]
I like what you did https://github.com/fuatakgun/kia_uvo/pull/150.

though I think we are talking about very different "pre-commit hooks".  I meant this type of pre-commit hook https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

made another pr https://github.com/fuatakgun/kia_uvo/pull/152 with a black issue for testing

**Comment by cdnninja** [comment]
Could you make a pull against my fork master? I want to confirm it works against someone else's fork as well.

**Comment by dahlb** [comment]
I added a PR but it looks like there is a conflict between your fork master and the main master for lint.yaml

**Comment by cdnninja** [comment]
I fixed the lint but it looks to be using your action not mine.  I will keep looking tonight.  They don't make this easy.

**Comment by cdnninja** [comment]
It now seems to work for a remote fork to commit black directly back to that branch.  Take a look at the example you cut and feel free to run another end to end example.

**Comment by dahlb** [comment]
I did another end to end and it seems very seamless, well done

**Comment by cdnninja** [comment]
I will create a PR for this update. @fuatakgun I will need you to create and store a personal access token into this repo.  Now we can either:

1. Use your personal token (shows up as all black corrections are you / a bot)
2. Use my token.  (shows up as me)
3. Create a dummy account with contributor access and use its token. 

The token will be encrypted and only accessible from a workflow.  The workflow however could be modified.  The token will also only have access to edit repos.

![image](https://user-images.githubusercontent.com/6373468/142337774-a504e915-8e7c-4e7d-998e-6026265ecd83.png)


Steps are here, both need to be done and I need the name of the token. Right now I called it PAT. 
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by cdnninja** [comment]
Removed token to get 157 merged.   Token will let checks re-run a second time to ensure everything is fixed.   Once token is added to the repo I will add it to the workflow.

**Comment by fuatakgun** [comment]
coming back to here, anything needed from me @cdnninja ?

**Comment by fuatakgun** [comment]
Created a repository secret named as `PAT`

**Comment by cdnninja** [comment]
I have added the token reference to the lint check.   Next PR should work correctly.
