### ISSUE TITLE
latest update throws error

### ISSUE THREAD

**Issue by Symbiot78** [fuatakgun/kia_uvo#329]
most recent update from today/yesterday throws this error after updating:

Error setting up entry <#redacted#> for kia_uvo
08:22:10 – (ERROR) Kia Uvo / Hyundai Bluelink (custom integration)
kia_uvo - Exception in update : 'resMsg' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 455, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] KeyError: 'resMsg'
08:22:10 – (ERROR) Kia Uvo / Hyundai Bluelink (custom integration)

**Comment by jvanhambelgium** [comment]
Slightly different error on my installation since I just updated to 1.7.0

Logger: custom_components.kia_uvo.Vehicle
Source: custom_components/kia_uvo/Vehicle.py:81
Integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: 20:14:44 (1 occurrences)
Last logged: 20:14:44

kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 455, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] **TypeError: string indices must be integers**

**Comment by digaus** [comment]
> Slightly different error on my installation since I just updated to 1.7.0
> 
> Logger: custom_components.kia_uvo.Vehicle Source: custom_components/kia_uvo/Vehicle.py:81 Integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues)) First occurred: 20:14:44 (1 occurrences) Last logged: 20:14:44
> 
> kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 455, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] **TypeError: string indices must be integers**

Same for me

**Comment by digaus** [comment]
Seemed to work for me now without any changes. Maybe it was a server issue
