### ISSUE TITLE
Missing sensors - v2.0.15

### ISSUE THREAD

**Issue by DJBenson** [fuatakgun/kia_uvo#410]
Following on from #397 

Since the re-write I'm still missing sensors, namely the tire pressure sensors. Still evaluating if anything else is missing.

UK user with a Kia EV.

**Comment by cdnninja** [comment]
v2.0.17 should add tire pressure. Can you confirm?

**Comment by Linwood-F** [comment]
I'm not the OP but did just install V2.0.17 for a US Kia EV6 and the tire pressure just shows "all" and state "Off".

**Comment by cdnninja** [comment]
> I'm not the OP but did just install V2.0.17 for a US Kia EV6 and the tire pressure just shows "all" and state "Off".

That is a different region so a seperate fix.   Based on the old code I don't think we ever implemented each wheel for kia USA.  Could you provide debug logging of your vehicle status:  Looking to see if it contains each wheel and what title.

**Comment by Linwood-F** [comment]
Does it require a lot of time before it shows something useful?   I didn't see anything at first, so did a service call for update.  just one line generated, so did a force update and got errors. 

I'm not sure what the "not enrolled" means in this context, since it is giving me sensors and correct data (well, mostly correct, odometer shows zero). 

I've attached the log.  This came with debug set as part the first readme, but expected a lot more data dumped.  Was there perhaps something else I do, I changed my configuration.yaml and restarted. 

Anyway, it's attached, happy to redo if need more data. 

[DebugLog.txt](https://github.com/fuatakgun/kia_uvo/files/9947617/DebugLog.txt)

**Comment by cdnninja** [comment]
Logging will need to be done via the 2.0 method which is listed here: https://github.com/fuatakgun/kia_uvo/tree/v2.0. It is a bit hard to find that until we promote 2.0 into the primary branch.   Not enrolled seems like your car doesn't support what it was trying to do.  Potentially a pay for service? Does this work in the native USA app?

**Comment by Linwood-F** [comment]
OK, got a big json dump (I think twice but didn't check precisely to see if same so here are both). Let me know if you need anything else.

Do you want me to try the force update again also? 

[DebugLog.txt](https://github.com/fuatakgun/kia_uvo/files/9947690/DebugLog.txt)

**Comment by cdnninja** [comment]
Your logs only have: `tirePressure":{"all":0}` so it looks like your region or car don't support each tire.  If seeing other issues still with force update please open a separate issue for that. I will keep this one focused around EU missing items.

**Comment by DJBenson** [comment]
@cdnninja the sensors showed up for me in 2.0.17 but of course until there is an issue with the tire pressure I can't say whether they are working or not (I've seen them work as my wife had a blowout recently and I got the alert in Home Assistant shortly after).

Will monitor but I think this can be considered closed now - should I close it or are there ongoing issues with other users?

**Comment by cdnninja** [comment]
We have issues now for the other items. I will close this out.  Thanks for testing this new version.  Really appreciate it.
