### ISSUE TITLE
KIA USA Support

### ISSUE THREAD

**Issue by cdnninja** [fuatakgun/kia_uvo#88]
To continue the conversation on #80 specific for Kia. @mbbush.

**Comment by mbbush** [comment]
I put the mock responses file at 
https://github.com/mbbush/kia_uvo/pull/1

**Comment by mbbush** [comment]
I can see a request to `https://owners.kia.com/apps/services/owners/getvehicleinfo.html/vehicleFeature/1/vehicleStatus/1/enrollment/1/maintenance/1/dtc/1` which uses that cookie, and a header named `vinkey`, which is a uuid, although I haven't figured out where it comes from yet. This request returns json containing lots of useful data about the car.

Still TODO:
* Figure out how to refresh the data
* make some sort of more organized collection of requests/responses and share them in a useful format. I use insomnia.rest at work for sharing "here's an api you can call manually", so I'll probably create an insomnia collection. It's the same idea as postman, but with some cool extra features. 

How similar or dissimilar does this sound to the way it works in CA or EU? I haven't read the existing source code yet; I should probably do that...

**Comment by mbbush** [comment]
ok, so this api is funky.

To login, you have to make a POST request, with a JSON body, but set the content type to `application/x-www-form-urlencoded`. All other combinations of sending the data I've tried (form data sent with the content type for form data, json with json content type), you don't get a response body, but you still get the session cookie. The one other thing that worked was sending form data with a single key consisting of the url-encoded json body, and no value. Yuck. 

Anyways, this works, and returns a body and a session cookie. Still working on the subsequent requests.
```
import requests
import json

payload = { 
  "userId": "user",
  "password": "PASSWORD",
  "userType": "1",
  "vin": "",
  "action": "authenticateUser"
  }
 
 r = requests.post('https://owners.kia.com/apps/services/owners/apiGateway', data=json.dumps(payload), headers={'Content-Type': 'application/x-www-form-urlencoded'})
 ```

**Comment by cdnninja** [comment]
It may be worth comparing to what the android app does.  It looks like this is front ended by aws amazon gateway.  If we can crack the key like the Hyundai usa integration I bet it will be easier in the long haul. 

It seems like two apis exist.  The website and the app.

**Comment by mbbush** [comment]
I'll get started on spying on the app, then. It's been a long time since I've dealt with intercepting SSL traffic, so I'm not sure how long it'll take me. 

I did see a couple properties in the manifest file that looked like they could be flipped to allow insecure requests/easy debugging, so maybe I'll try that first.

Why do you say you think this is "front ended by aws amazon gateway"? I definitely got the impression that this was _not_ using some of the aws-managed products like Api Gateway or Cognito, simply because it uses a funky non-standard auth mechanism, and the aws-managed products generally do a pretty good job of conforming to standards. I also didn't see any aws-like response headers.

**Comment by tchoward** [comment]
I seem to get past login, but then I see the same as above.

> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/kia_uvo/__init__.py", line 134, in async_setup_entry
>     vehicle: Vehicle = Vehicle(
>   File "/config/custom_components/kia_uvo/Vehicle.py", line 40, in __init__
>     self.model = token.vehicle_model
> AttributeError: 'Token' object has no attribute 'vehicle_model'

_

**Comment by cdnninja** [comment]
@mbbush have you had a chance to look at this?

**Comment by mbbush** [comment]
No, not yet. I've been busy with other things. If someone else wants to
look they are welcome to do so.

**Comment by cdnninja** [comment]
Commits have been done to get this closer to functional. Please provide feedback and future PRs.  Thanks to everyone involved getting it this far.

**Comment by dahlb** [comment]
I put in PRs for what I think is everything populating except temperature, which I'm working on but will take me a few days (first F in code base of C)

**Comment by cdnninja** [comment]
Huge thank you @dahlb this has really pushed the USA Kia support forward.  Great to see!

**Comment by dahlb** [comment]
@mbbush I don't know how to get the Uvo USA apk, but from the previous comments I'm guessing you found it.  Can you point me to where you got it or throw your copy up somewhere for me to grab which would be even better as I assume it was already modified by apk-mitm

**Comment by mbbush** [comment]
Since I'm in the USA, I just downloaded it from google play and then used ADB to pull it off the phone. 

I remember that I tried several different tools and really struggled with them, before finding the one I mentioned in a comment above, which made it really easy. I don't remember whether I needed some of the partial work I'd done with the other tools to work with the good one. 

The apk itself is also packaged in several layers. There are actually four apks, each containing different components, but it looks like the most relevant parts are in the base.apk

It looks like I have several versions, some of which are for x86 (to use on the emulator) and some of which are for arm. Some are quite possibly patched by something, some are zipped, some are extracted. It's a mess. But I'm happy to share the mess with you! https://mega.nz/file/TR5ERATL#oIPtw-89kWz0ZoYTPE0WN5F9YJammdOd4OJbffHhPKg

**Comment by dahlb** [comment]
@mbbush thanks base.apk worked great and helped me finish force update

hoping to populate these methods next one at a time
lock_action
start_climate
start_charge

**Comment by Ceer123** [comment]
Thanks for the work on this so far.  My setup is working pretty good now.  One thing I noticed was every time there is an update all the sensors switch to Unavailable for about 4 seconds.  Is this a known issue?  If not I will add some logs.
![image](https://user-images.githubusercontent.com/16777301/141222158-11376f22-e253-479a-a084-82ca9e55b531.png)

**Comment by dahlb** [comment]
I haven't played with it enough to notice that. I know the auth sessions
need better error handling, ie if I log in on my phone then use the HA, HA
has an invalid session and doesn't recover without restarting or waiting an
hour.  But I'm focusing on some of the service actions next and will
revisit the auth issues after that.

**Comment by tchoward** [comment]
Thanks for all the work on this...

What I am seeing:
1. When my car is not being driven and not charging (PHEV) it shows battery, range, etc as zero.
![image](https://user-images.githubusercontent.com/64616204/141313130-7ea17c1f-c771-4640-8e27-af43f163d251.png)
2. Errors from the log are below. 
```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: November 10, 2021, 6:47:13 AM (33 occurrences)
Last logged: 8:52:27 AM

Exception in update when dispatching 'kia_uvo_update_0': () Traceback (most recent call last): File "/config/custom_components/kia_uvo/KiaUvoEntity.py", line 21, in update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state if (state := self.state) is None: File "/config/custom_components/kia_uvo/sensor.py", line 100, in state return self.vehicle.kia_uvo_api.get_temperature_range_by_region()[int(value, 16)] ValueError: invalid literal for int() with base 16: '0xLOW'
```

**Comment by dahlb** [comment]
@tchoward 

1) I believe this is the same as the issue tracked here https://github.com/fuatakgun/kia_uvo/issues/55 and I've seen it on my EV too it is an artifact of Kia's api but work arounds are being discussed

2) can you add that stack trace to https://github.com/fuatakgun/kia_uvo/pull/115 that is the pr to address temperatures in USA and currently that pr wouldn't handle that scenario of the car's temp being too low, but if your willing to test a fix I could add an improvement to that so it does

**Comment by dahlb** [comment]
added the other actions in a pr has every other action; once I figured out the offset being -5.0 instead of -5 was the problem for a while the rest was very fast

still want to fix
1) validate and log errors for responses that aren't successful, will be helpful in next fix too
2) auth sessions errors handled gracefully (create new session and keep working)
3) check status of action until finish and then trigger update for attributes

**Comment by dahlb** [comment]
@cdnninja I think this is fully implemented now, unless I missed something?

**Comment by cdnninja** [comment]
Nope. I think we can close this an open issues if needed great work @dahlb  and @mbbush.  Great to see this working.
